apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: spring-boot
  namespaceSelector:
    matchNames:
      - devops
  endpoints:
  - port: http
    path: /student/actuator/prometheus
    interval: 15s
